/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Classes.JogoDaForca;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Keslley
 */
public class Aplicacao extends javax.swing.JFrame {

    private JogoDaForca colecao;
    private int tentativas = 7;

    public Aplicacao() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDLetra = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFLetra = new javax.swing.JTextField();
        jBConfirmar = new javax.swing.JButton();
        jLDica = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLPalavra = new javax.swing.JLabel();
        jLLetra = new javax.swing.JLabel();
        jLPalpite = new javax.swing.JLabel();
        jLErros = new javax.swing.JLabel();
        jLPal2 = new javax.swing.JLabel();
        jLLet2 = new javax.swing.JLabel();
        jLTentativas2 = new javax.swing.JLabel();
        jLPalpite2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLForca = new javax.swing.JLabel();
        jLDica2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMJogo = new javax.swing.JMenu();
        jMINovoJogo = new javax.swing.JMenuItem();
        jMAjuda = new javax.swing.JMenu();
        jMIDica = new javax.swing.JMenuItem();
        jMSair = new javax.swing.JMenu();
        jMISair = new javax.swing.JMenuItem();

        jDLetra.setTitle("Digite uma Letra");

        jPanel2.setToolTipText("");

        jLabel1.setText("Letra:");

        jTFLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaCampo(evt);
            }
        });

        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jTFLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jBConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addComponent(jBConfirmar)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jDLetraLayout = new javax.swing.GroupLayout(jDLetra.getContentPane());
        jDLetra.getContentPane().setLayout(jDLetraLayout);
        jDLetraLayout.setHorizontalGroup(
            jDLetraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDLetraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDLetraLayout.setVerticalGroup(
            jDLetraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDLetraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Forca");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLDica.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLDica.setText("Dica:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        jLPalavra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLPalavra.setText("Palavra:");

        jLLetra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLLetra.setText("Letras Usadas:");

        jLPalpite.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLPalpite.setText("Ultimo Palpite:");

        jLErros.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLErros.setText("Tentativas Restantes:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLLetra, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLPalavra, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLPalpite, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLErros, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPalpite2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPal2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLLet2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTentativas2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPalavra)
                    .addComponent(jLPal2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLLetra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLPalpite))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLLet2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLPalpite2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLErros, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTentativas2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logotipo.jpg"))); // NOI18N

        jLForca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/forca.jpg"))); // NOI18N
        jLForca.setLabelFor(jLForca);
        jLForca.setDisabledIcon(null);

        jMJogo.setText("Jogo");

        jMINovoJogo.setText("Novo Jogo");
        jMINovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINovoJogoActionPerformed(evt);
            }
        });
        jMJogo.add(jMINovoJogo);

        jMenuBar1.add(jMJogo);

        jMAjuda.setText("Ajuda");

        jMIDica.setText("Dica");
        jMIDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDicaActionPerformed(evt);
            }
        });
        jMAjuda.add(jMIDica);

        jMenuBar1.add(jMAjuda);

        jMSair.setText("Sair");

        jMISair.setText("Sair do Jogo");
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        jMSair.add(jMISair);

        jMenuBar1.add(jMSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLForca, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLDica)
                            .addGap(18, 18, 18)
                            .addComponent(jLDica2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLForca, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDica2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDica))
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jMIDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDicaActionPerformed
         
            //if(tentativas < 6){
           // jLDica2.setText(colecao.retornaDicas());
            //}else{
            //   JOptionPane.showMessageDialog(this, "Tente escolher uma letra antes de receber uma dica!");
            // }
    }//GEN-LAST:event_jMIDicaActionPerformed

    private void jMINovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINovoJogoActionPerformed
        colecao = new JogoDaForca();
        colecao.inicioJogo();
        insereImagem("/Imagens/forca.jpg/");
        char letra = 'a';
        jLPal2.setText(colecao.exibiAcertos());
        jLTentativas2.setText(" " + tentativas);

        while (!colecao.jogoAcabado()) {
            try {
                letra = JOptionPane.showInputDialog(this, "Digite uma letra!").toUpperCase().charAt(0);
                

            } catch (NullPointerException ex) {
                colecao.setTotErros(7);
                JOptionPane.showMessageDialog(this, "Fim de jogo!");

            }
            colecao.setUsadas(letra);
            jLLet2.setText(colecao.letrasUsadas());
            
            if (colecao.getTotErros() < 7) {
                if (colecao.encontrou(letra)) {
                    jLPalpite2.setText(letra + " (Correto)");
                    JOptionPane.showMessageDialog(this, "Você acerto meu querido!");
                } else {
                    jLPalpite2.setText(letra + " (Errado)");
                    tentativas--;
                    colecao.somadosErros();
                    
                    if(colecao.getTotErros()>=2){
                        jLDica2.setText(colecao.retornaDicas());
                    }

                    switch (colecao.getTotErros()) {
                        case 1:
                            insereImagem("/Imagens/forca2.jpg/");
                            break;
                        case 2:
                            insereImagem("/Imagens/forca3.jpg/");
                            break;
                        case 3:
                            insereImagem("/Imagens/forca4.jpg/");
                            break;
                        case 4:
                            insereImagem("/Imagens/forca5.jpg/");
                            break;
                        case 5:
                            insereImagem("/Imagens/forca6.jpg/");
                            break;
                        case 6:
                            insereImagem("/Imagens/forca7.jpg");
                            break;
                    }

                    JOptionPane.showMessageDialog(this, "Você errou meu amigo!");
                }
            }

            jLPal2.setText(colecao.exibiAcertos());
            jLTentativas2.setText(" " + tentativas);
        }
        
        if(colecao.ganhastes()){
            JOptionPane.showMessageDialog(this, "Você ganhou meu amigo!!");
            resetejogo();
            insereImagem("/Imagens/forca.jpg");
        }else{
            JOptionPane.showMessageDialog(this, "Você perdeu meu amigo!!");
            resetejogo();
            insereImagem("/Imagens/forca.jpg");
        }

    }//GEN-LAST:event_jMINovoJogoActionPerformed

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMISairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            //colecao.adicionaPalavras();
    }//GEN-LAST:event_formWindowOpened

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed

       


    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void validaCampo(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaCampo
        char tecla = evt.getKeyChar();
        if (Character.isDigit(tecla) && tecla != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_validaCampo

    private void resetejogo() {
        jLPal2.setText(null);
        jLLet2.setText(null);
        jLTentativas2.setText(null);
        jLPalpite2.setText(null);
        jLDica2.setText(null);

    }

    private void insereImagem(String imagem) {
        jLForca.setIcon(new ImageIcon(getClass().getResource(imagem)));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JDialog jDLetra;
    private javax.swing.JLabel jLDica;
    private javax.swing.JLabel jLDica2;
    private javax.swing.JLabel jLErros;
    private javax.swing.JLabel jLForca;
    private javax.swing.JLabel jLLet2;
    private javax.swing.JLabel jLLetra;
    private javax.swing.JLabel jLPal2;
    private javax.swing.JLabel jLPalavra;
    private javax.swing.JLabel jLPalpite;
    private javax.swing.JLabel jLPalpite2;
    private javax.swing.JLabel jLTentativas2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMAjuda;
    private javax.swing.JMenuItem jMIDica;
    private javax.swing.JMenuItem jMINovoJogo;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenu jMJogo;
    private javax.swing.JMenu jMSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFLetra;
    // End of variables declaration//GEN-END:variables
}
